//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class AspNetEntities : DbContext
{
    public AspNetEntities()
        : base("name=AspNetEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<pomdept2> pomdept2 { get; set; }
    public virtual DbSet<pomflow1> pomflow1 { get; set; }
    public virtual DbSet<pomflow2> pomflow2 { get; set; }
    public virtual DbSet<pompersn1> pompersn1 { get; set; }
}
